### PR TITLE
fix(orb-ui): unable edit {entity} no tags

### LINKED ISSUE #183: Agent Groups: Although an error message appears, it is possible to create two identical key and value pairs
A error message is being displayed but double key-value creation is allowed

Check: https://drive.google.com/file/d/1MvdknGxMO03T9Npfqo35hUCbqvXp44ib/view?usp=sharing

Last Commit: 50df003b85d894ec2f3ba7d5d7a913eec1e82e4e

### LINKED ISSUE #191: Agent Groups: Unable to edit existing agent group
Check: https://drive.google.com/file/d/1RJw6d3tK2z1SbNaXeH9hO0rnyULIaXOS/view?usp=sharing

Last Commit: 50df003b85d894ec2f3ba7d5d7a913eec1e82e4e

### LINKED ISSUE #366: Agent Groups: When all tags are removed, agent match is not updated
When an agent group is created or edited, if tag(s) are included and then all are removed, agent match is not updated

### LINKED ISSUE #405: All pages: Creation of empty tags is enabled
It is possible to create tags just with spaces " ":" ".
Tags should have a regex (it's not good practice to allow the user to put whatever they want.)

### LINKED ISSUE #434: Created tags we the same key name are being condensed into only one tag no matter how many we have.

### LINKED ISSUE #512: Unable to edit sink without tag
if sink doesn't have tag, edition is not enabled

### PR DESCRIPTION
**Pull request by gpazuch**
resolves #512
resolves #191 
resolves #183
resolves #366
resolves #434
resolves #405

### CODE REVIEW

**Review by iatdaitan — APPROVED** [review]
lgtm

**Review by iatdaitan — APPROVED** [review]
lgtm

**Comment by manrodrigues** [comment]
agent-tag

**Comment by manrodrigues** [comment]
#512  - ok 

agent-tag

**Comment by manrodrigues** [comment]
#191 - ok

agent-tag

**Comment by manrodrigues** [comment]
#183  - ok


agent-tag

**Comment by manrodrigues** [comment]
#366 - not working

agent-group-tag

**Comment by manrodrigues** [comment]
#434 - working as described in option 1.
same-tag

**Comment by manrodrigues** [comment]
#405 - not working yet

empty-tags

**Pull request merged**
