### PR TITLE
feat(orb-ui orb-tests): Add data-* attr to automated testing

### PR DESCRIPTION
**Pull request by gpazuch**
@manrodrigues I've completed the Sink Add Page with basic tag info and also updated the `README.md`.  

I've created a page with examples [](https://github.com/ns1labs/orb/wiki/UI-QA-Automation-Tags), but you can check further additions [here](https://github.com/ns1labs/orb/pull/222/files) :)  

*(This Pull Request is good to be merged, or the branch preserved until all pages have their respective automation tags.)*  

>Add data-orb-qa-id to some elements of `sink.add.component` for testing.

>@manrodrigues besides id for static and dynamic content, such as tables, is there any other type of metadata you could use?

>I've added just a few tags for you to test and give some feedback. There are a few links below for reference. :)

>https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*

>https://www.techiediaries.com/add-access-html-data-attribute-angular/

>https://angular.io/guide/template-syntax

### CODE REVIEW

**Comment by daitan-rovaris** [comment]
@gpazuch does this PR relates or requires this one:
https://github.com/ns1labs/orb/pull/221 ?

**Comment by gpazuch** [comment]
> @gpazuch does this PR relates or requires this one:
> #221 ?

Thx for the heads up, fixed it.

**Comment by gpazuch** [comment]
@dscabral Failed Go build. I should be able to click re-run and it end up working, right?

**Review by daitan-rovaris — APPROVED** [review]
lgtm

**Review by manrodrigues — APPROVED** [review]
I think this tag is enough. Many thanks.

**Pull request merged**
