### PR TITLE
fix(orb-ui): Policy Details View

### LINKED ISSUE #695: Policy: Policies details should display relevant information (handlers, pcap, filters)
Once user have a lot of policies created, agent policy details  should help the user to know what kind of policy it is. The information that currently appears doesn't help with anything.

image

### PR DESCRIPTION
**Pull request by gpazuch**
* Add section input type and tap names 
* Add section for listing of handlers names
Resolves #695

### CODE REVIEW

**Comment by gpazuch** [comment]
@weyrick should I list handler specifics? maybe this view could show a codebox with the yaml/json for agent.

**Comment by weyrick** [comment]
yeah maybe let's just start with the codebox json view. we probably want this anyway, and later on can add an additional view that tries to make it look nicer

**Comment by gpazuch** [comment]
image
with a few more tweaks to css we can have this accordion looking nice too

**Comment by gpazuch** [comment]
image

**Comment by gpazuch** [comment]
I think we might need a different view for this, as the number of handlers could cause issues here, probably some sort of table, or having this view changed from the modal to a dedicated page

**Review by iatdaitan — APPROVED** [review]
Approved.

@manrodrigues pleas, upon test, if you didn't find any bug but do have any suggestion of improvement, please add an enhancement issue. We are working on an improvement for this section for the next couple sprints.

**Comment by manrodrigues** [comment]
@iatdaitan ok. sure. @gpazuch please, squash and merge this into develop and move card to QA. Thanks.

**Pull request merged**
