### PR TITLE
feat(orb-ui): Agent View Enhancements

### PR DESCRIPTION
**Pull request by gpazuch**
* new header section for agent view
* add agent capabilities list
* update tags display
* update provisioning command card
* update policy/datasets card
* update group name list card

### CODE REVIEW

**Comment by gpazuch** [comment]
image

**Comment by gpazuch** [comment]
image

**Comment by gpazuch** [comment]
image

**Comment by gpazuch** [comment]
image

**Comment by iatdaitan** [comment]
@gpazuch once the user click on the Agent Group name lets redirect them to the existing modal on Agent Groups list view page.

**Comment by gpazuch** [comment]
image

**Review by iatdaitan — APPROVED** [review]

**Pull request merged**
