### PR TITLE
fix(orb-ui): #528 add company name field to register page

### LINKED ISSUE #528: Add company to register page

### PR DESCRIPTION
**Pull request by gpazuch**
resolves #528 add company name field to register page

### CODE REVIEW

**Review by iatdaitan — APPROVED** [review]
lgtm

**Comment by manrodrigues** [comment]
working fine

**Comment by manrodrigues** [comment]
image

**Comment by manrodrigues** [comment]
There is any reason why company is sent on request but full name isn''t?

**Comment by manrodrigues** [comment]
We also should have "*" for required fields, because user is enabled (should be?) to register an account without name and company.

**Pull request merged**
