### PR TITLE
feat(orb-ui): #641 change color of 'mock' string

### PR DESCRIPTION
**Pull request by gpazuch**
image -- using \<mark\/\> tag

mark text where user could/should change interface

### CODE REVIEW

**Comment by gpazuch** [comment]
Alternatively, we could change just the font to a brighter color instead of <mark>ing it.

**Comment by weyrick** [comment]
I think it's good enough to change the text color, not have the background changed. Also the text "Replace mock interface with host network interface" should be that same text color probably?

**Comment by gpazuch** [comment]
image
Oh ok, lemme take a screenshot of just the text color.

**Comment by gpazuch** [comment]
@weyrick 
image

**Comment by gpazuch** [comment]
image
@weyrick

**Comment by gpazuch** [comment]
image

**Review by weyrick — APPROVED** [review]
awesome

**Pull request merged**
