### PR TITLE
fix(orb-ui): #1018 - Improve policy error msgs

### PR DESCRIPTION
**Pull request by gbottega**
issue #1018

Besides the issue with the yaml error message when trying to create the policy, the page was going to the next step even with errors:

https://user-images.githubusercontent.com/101733592/177845417-bb3bdf71-50fb-4cbc-864c-4d6462cb9dfb.mp4

After fix, a more detailed error message is shown, and we stay at the current step:

image

The error messages shown when trying to edit the policies where also improved. The error with JSON was not even verified before:

image

image

### CODE REVIEW

**Review by etaques — APPROVED** [review]
Well done!
LGTM

**Review by gpazuch — APPROVED** [review]
💯

**Review by lpegoraro — APPROVED** [review]
LGTM

**Review by manrodrigues — APPROVED** [review]
LGTM

**Pull request merged**
