### PR TITLE
feat(orb-ui): add style to forgot-password page

### LINKED ISSUE #524: Style forgot my password page

### PR DESCRIPTION
**Pull request by gpazuch**
resolves #524

### CODE REVIEW

**Review by iatdaitan — APPROVED** [review]
lgtm

**Comment by manrodrigues** [comment]
Style is ok, but Request Password button is not working

**Comment by manrodrigues** [comment]
forgotpass

**Comment by manrodrigues** [comment]
note that there are no requests


norequest

**Pull request merged**
