### PR TITLE
feat(orb-ui): Remove Dataset menu item

### PR DESCRIPTION
**Pull request by gpazuch**
* remove dataset menu item

Datasat now acessible via Agent Policy View only.

### CODE REVIEW

**Comment by gpazuch** [comment]
image

**Comment by gpazuch** [comment]
image

**Comment by gpazuch** [comment]
https://www.figma.com/file/5jZNpc8JMsY2Tj3OQJzgxt/Orb-Product-Portal-UI?node-id=276%3A1746

**Review by lpegoraro — APPROVED** [review]
LGTM

**Pull request merged**
